---
password:
  type: string
  description: "The password to log into the Jumpbox or AD DC"
  secret: true
port:
  type: integer
  description: "Port to connect to Veeam on"
  default: 9399
scheme:
  type: string
  description: "Scheme/transport to use for connection (http, https)"
  default: "http"
server:
  type: string
  description: "Hostname / IP address of the veeam server"
ssl_verify:
  type: boolean
  description: "Should SSL host certificate be certified"
  default: false
username:
  type: string
  description: "The username to log into the Jumpbox or AD DC"
